"""Export GatedBiCrossAttention model from PyTorch to TFLite INT8.

Usage:
    python export_model.py

Pipeline: PyTorch -> ONNX -> TensorFlow SavedModel -> TFLite INT8 -> C header

The Tier2 model takes TWO 11-dim inputs (left, right), not a single 28-dim
vector.  The 6 relative features are NOT used by this model.
"""
from __future__ import annotations

import os
import sys

import numpy as np

# Allow imports from glove_relay/src
sys.path.insert(
    0, os.path.join(os.path.dirname(__file__), "../../glove_relay/src")
)

import torch  # noqa: E402
from models.tier2_cross_attn import GatedBiCrossAttention  # noqa: E402

INPUT_DIM = 11   # per hand
NUM_CLASSES = 46


def export_to_onnx(model: GatedBiCrossAttention, onnx_path: str) -> None:
    """Export PyTorch model to ONNX with two separate inputs."""
    model.eval()
    dummy_left = torch.randn(1, INPUT_DIM)
    dummy_right = torch.randn(1, INPUT_DIM)

    torch.onnx.export(
        model,
        (dummy_left, dummy_right),
        onnx_path,
        input_names=["left", "right"],
        output_names=["output"],
        dynamic_axes={
            "left": {0: "batch"},
            "right": {0: "batch"},
            "output": {0: "batch"},
        },
        opset_version=13,
    )
    print(f"ONNX exported: {onnx_path}")


def convert_to_tflite(onnx_path: str, tflite_path: str) -> None:
    """Convert ONNX model to TFLite INT8 via TensorFlow."""
    import onnx
    from onnx_tf.backend import prepare
    import tensorflow as tf

    onnx_model = onnx.load(onnx_path)
    tf_rep = prepare(onnx_model)
    tf_dir = os.path.splitext(onnx_path)[0] + "_tf"
    tf_rep.export_graph(tf_dir)

    converter = tf.lite.TFLiteConverter.from_saved_model(tf_dir)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    # Representative dataset for INT8 calibration
    def representative_dataset():
        for _ in range(100):
            yield [
                np.random.randn(1, INPUT_DIM).astype(np.float32),
                np.random.randn(1, INPUT_DIM).astype(np.float32),
            ]

    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS_INT8
    ]
    converter.inference_input_type = tf.float32
    converter.inference_output_type = tf.float32

    tflite_model = converter.convert()
    with open(tflite_path, "wb") as f:
        f.write(tflite_model)
    print(f"TFLite INT8 exported: {tflite_path} ({len(tflite_model)} bytes)")


def tflite_to_c_header(tflite_path: str, header_path: str) -> None:
    """Embed TFLite binary as a C array in a header file."""
    with open(tflite_path, "rb") as f:
        data = f.read()

    with open(header_path, "w") as f:
        f.write("// Auto-generated by export_model.py\n")
        f.write(f"// Model size: {len(data)} bytes\n\n")
        f.write("#pragma once\n\n")
        f.write(f"const unsigned int model_data_len = {len(data)};\n")
        f.write("alignas(16) const unsigned char model_data[] = {\n")
        for i, byte in enumerate(data):
            if i % 16 == 0:
                f.write("  ")
            f.write(f"0x{byte:02x}, ")
            if i % 16 == 15:
                f.write("\n")
        f.write("\n};\n")
    print(f"C header: {header_path}")


def main() -> None:
    model = GatedBiCrossAttention(d_model=32, num_classes=NUM_CLASSES)

    # Try to load trained weights
    checkpoint = os.path.join(
        os.path.dirname(__file__),
        "../../glove_relay/models/tier2_cross_attn.pth",
    )
    if os.path.exists(checkpoint):
        model.load_state_dict(
            torch.load(checkpoint, map_location="cpu", weights_only=True)
        )
        print(f"Loaded weights from {checkpoint}")
    else:
        print("WARNING: No trained weights found, exporting random model")

    base = os.path.join(
        os.path.dirname(__file__), "../p4_base_station/p4_firmware/model"
    )
    os.makedirs(base, exist_ok=True)

    onnx_path = os.path.join(base, "tier2.onnx")
    tflite_path = os.path.join(base, "tier2_int8.tflite")
    header_path = os.path.join(base, "model_data.h")

    export_to_onnx(model, onnx_path)
    convert_to_tflite(onnx_path, tflite_path)
    tflite_to_c_header(tflite_path, header_path)

    print("\nDone. Files:")
    print(f"  ONNX:   {onnx_path}")
    print(f"  TFLite: {tflite_path}")
    print(f"  Header: {header_path}")


if __name__ == "__main__":
    main()
