# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glove_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glove_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10glove_data.proto\x12\ndata_glove\"\xc2\x01\n\tGloveData\x12\x11\n\ttimestamp\x18\x01 \x01(\r\x12\x19\n\rhall_features\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x18\n\x0cimu_features\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x19\n\rflex_features\x18\x04 \x03(\x02\x42\x02\x10\x01\x12\x15\n\rl1_gesture_id\x18\x05 \x01(\r\x12\x15\n\rl1_confidence\x18\x06 \x01(\x02\x12\x14\n\x0cl2_requested\x18\x07 \x01(\x08\x12\x0e\n\x06status\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glove_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GLOVEDATA'].fields_by_name['hall_features']._loaded_options = None
  _globals['_GLOVEDATA'].fields_by_name['hall_features']._serialized_options = b'\020\001'
  _globals['_GLOVEDATA'].fields_by_name['imu_features']._loaded_options = None
  _globals['_GLOVEDATA'].fields_by_name['imu_features']._serialized_options = b'\020\001'
  _globals['_GLOVEDATA'].fields_by_name['flex_features']._loaded_options = None
  _globals['_GLOVEDATA'].fields_by_name['flex_features']._serialized_options = b'\020\001'
  _globals['_GLOVEDATA']._serialized_start=33
  _globals['_GLOVEDATA']._serialized_end=227
# @@protoc_insertion_point(module_scope)
