# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glove_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glove_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10glove_data.proto\x12\x0c\x65\x63hoglove_v5\"\xdf\x01\n\tGloveData\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\r\x12\x0f\n\x07hand_id\x18\x03 \x01(\r\x12\x0c\n\x04\x66lex\x18\x04 \x03(\x02\x12\x0b\n\x03imu\x18\x05 \x03(\x02\x12\x15\n\rl1_gesture_id\x18\x06 \x01(\r\x12\x15\n\rl1_confidence\x18\x07 \x01(\x02\x12\x10\n\x08relative\x18\x08 \x03(\x02\x12\x18\n\x10tier2_gesture_id\x18\t \x01(\r\x12\x18\n\x10tier2_confidence\x18\n \x01(\x02\x12\x0e\n\x06status\x18\x0b \x01(\t\"\x9c\x01\n\x0eReceiverPacket\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0f\n\x07tick_id\x18\x02 \x01(\r\x12%\n\x04left\x18\x03 \x01(\x0b\x32\x17.echoglove_v5.GloveData\x12&\n\x05right\x18\x04 \x01(\x0b\x32\x17.echoglove_v5.GloveData\x12\x19\n\x11relative_features\x18\x05 \x03(\x02\"\x88\x01\n\x11\x42\x61seStationStatus\x12\x14\n\x0c\x63\x36_connected\x18\x01 \x01(\x08\x12\x10\n\x08p4_ready\x18\x02 \x01(\x08\x12\x11\n\tcpu_usage\x18\x03 \x01(\x02\x12\x11\n\tmem_usage\x18\x04 \x01(\x02\x12\x10\n\x08uptime_s\x18\x05 \x01(\r\x12\x13\n\x0b\x61\x63tive_tier\x18\x06 \x01(\r\"\x8a\x02\n\x11\x42\x61seStationPacket\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0f\n\x07tick_id\x18\x02 \x01(\r\x12%\n\x04left\x18\x03 \x01(\x0b\x32\x17.echoglove_v5.GloveData\x12&\n\x05right\x18\x04 \x01(\x0b\x32\x17.echoglove_v5.GloveData\x12\x19\n\x11relative_features\x18\x05 \x03(\x02\x12\x18\n\x10tier2_gesture_id\x18\x06 \x01(\r\x12\x18\n\x10tier2_confidence\x18\x07 \x01(\x02\x12\x35\n\x0c\x62\x61se_station\x18\x08 \x01(\x0b\x32\x1f.echoglove_v5.BaseStationStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glove_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GLOVEDATA']._serialized_start=35
  _globals['_GLOVEDATA']._serialized_end=258
  _globals['_RECEIVERPACKET']._serialized_start=261
  _globals['_RECEIVERPACKET']._serialized_end=417
  _globals['_BASESTATIONSTATUS']._serialized_start=420
  _globals['_BASESTATIONSTATUS']._serialized_end=556
  _globals['_BASESTATIONPACKET']._serialized_start=559
  _globals['_BASESTATIONPACKET']._serialized_end=825
# @@protoc_insertion_point(module_scope)
